import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "on-error-container": "var(--on-error-container)",
        "error": "var(--error)",
        "surface-variant": "var(--surface-variant)",
        "secondary-container": "var(--secondary-container)",
        "surface-bright": "var(--surface-bright)",
        "inverse-primary": "var(--inverse-primary)",
        "outline": "var(--outline)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "on-primary-container": "var(--on-primary-container)",
        "tertiary": "var(--tertiary)",
        "background": "var(--background)",
        "on-primary": "var(--on-primary)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "secondary": "var(--secondary)",
        "on-secondary-container": "var(--on-secondary-container)",
        "on-secondary": "var(--on-secondary)",
        "primary-container": "var(--primary-container)",
        "surface-tint": "var(--surface-tint)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "secondary-fixed": "var(--secondary-fixed)",
        "on-surface": "var(--on-surface)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "on-background": "var(--on-background)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "on-surface-variant": "var(--on-surface-variant)",
        "surface-dim": "var(--surface-dim)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "on-error": "var(--on-error)",
        "surface-container": "var(--surface-container)",
        "surface-container-high": "var(--surface-container-high)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "surface-container-low": "var(--surface-container-low)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "surface": "var(--surface)",
        "primary-fixed": "var(--primary-fixed)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "error-container": "var(--error-container)",
        "tertiary-container": "var(--tertiary-container)",
        "inverse-surface": "var(--inverse-surface)",
        "surface-container-highest": "var(--surface-container-highest)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "outline-variant": "var(--outline-variant)",
        "primary": "var(--primary)",
        "on-tertiary": "var(--on-tertiary)",
        "brand-deep-blue": "var(--brand-deep-blue)",
        "brand-teal": "var(--brand-teal)",
        "brand-amber": "var(--brand-amber)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      maxWidth: {
        xs: "20rem",
        sm: "24rem",
        md: "28rem",
        lg: "32rem",
        xl: "36rem",
        "2xl": "42rem",
        "3xl": "48rem",
        "4xl": "56rem",
        "5xl": "64rem",
        "container-max": "1200px",
      },
      spacing: {
        lg: "40px",
        xs: "4px",
        md: "24px",
        sm: "12px",
        xl: "64px",
        base: "8px",
        safe: "env(safe-area-inset-bottom, 20px)",
        "container-max": "1200px",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "60px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      animation: {
        "slide-up": "slideUp 0.2s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "bounce-gentle": "bounceGentle 2s infinite",
      },
      keyframes: {
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        bounceGentle: {
          "0%, 100%": { transform: "translateY(-10%)", animationTimingFunction: "cubic-bezier(0.8,0,1,1)" },
          "50%": { transform: "none", animationTimingFunction: "cubic-bezier(0,0,0.2,1)" },
        },
      },
    },
  },
  plugins: [],
};
export default config;
